# -*- coding: utf-8 -*-
"""AI CW2 Heartstroke

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnVXbHfAA-J_Wm82bYB9G-IlWP5RcniK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install scikit-learn
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset1-HeartAttack.csv')

print (df.head())
print (df.columns)

X= df.iloc[:,:-1].values
print(X[0:11,:])
y = df['HeartDiseaseorAttack'].values

print(y[0:10])
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
predicted=model
predicted=model.predict([[9,1,1,1,40,1,0,0,0,1,0,5,18,15]])
print("Predicted Value:", predicted)

classifier = GaussianNB()
classifier.fit(X_train, y_train)

classifier.predict(X_test)

np.array(y_test)

Y_pred= classifier.predict(X_test)
classifier.score(X_test,y_test)

from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, Y_pred)
cr = classification_report(y_test, Y_pred)
print(cm)
print(cr)