# -*- coding: utf-8 -*-
"""AI Diabetes CW2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rzI-cSPLWq4Kj7QUyBgTsHrRnq6StoMM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset1 Diabetes .csv')
print (df.head(5))
print(df.columns)

# prompt: from the diabetes column swap all the 2 to 1

df['Diabetes'] = df['Diabetes'].replace(2, 1)
print(df.head(253681))

X= df.iloc[:,:-1].values
print(X[0:11,:])
y = df['Diabetes'].values

print(y[0:10])
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn import tree
model=tree.DecisionTreeClassifier()
model.fit(X_train,y_train)

from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

classifier.predict(X_test)

np.array(y_test)

classifier.predict(X_test)

np.mean(Y_pred==y_test)

from sklearn.metrics import confusion_matrix, classification_report
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, Y_pred)
cr = classification_report(y_test, Y_pred)
print(cm)x`
print(cr)

import numpy as np

# Taking user inputs
HD = int(input("Enter Heart Disease: (No=0, Yes=1): "))
HB = int(input("High Blood Pressure: (No=0, Yes=1): "))
HC = int(input("High cholesterol: (No=0, Yes=1): "))
BMI = int(input("Enter BMI: "))
PhyAct = int(input("Physical activity: (No=0, Yes=1): "))
Fruits = int(input("Fruits: (Yes=1, No=0): "))
Veggies = int(input("Veggies: (Yes=1, No=0): "))
DiffWalk = int(input("Difficulty Walking: (Yes=1, No=0): "))
Age = int(input("Enter Age: (18-24=1, 25-30=2, 31-35=3, 36-42=4, 43-48=5, 49-54=6, 55-60=7, 60-64=8, 65-70=9, 70-76=10, 76-80=11, Above 80=12): "))
Education = int(input("Enter Education: Never Attended School=1, Elementary school=2, Some HighSchool=3, HighSchool Graduate=4, Some College=5, University=6): "))
Income = int(input("Enter Income: Less than 10k=1, 10k-15k=2, 15k-20k=3, 20k-25k=4, 25k-30k=5, 35k-50k=6, 50k-75k=7, 75k More=8): "))

# Creating an input array
arr = np.array([HD, HB, HC, BMI, PhyAct, Fruits, Veggies, DiffWalk, Age, Education, Income]).reshape(1, 11)

# Assuming classifier is already defined and trained
arr_pred = classifier.predict(arr)

print("\n")
# Printing the predicted results
if arr_pred == 1:
    print("Yes Diabetes = Yes\n")
else:
    print("No Diabetes = No\n")