# -*- coding: utf-8 -*-
"""Heart Disease Model AI Assigment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186GjCrp6hEHAAF5j92MW9Dc6povJNe0H
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install scikit-learn
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset1 HeartDiseaseAttack.csv')

print (df.head())
print (df.columns)

X= df.iloc[:,:-1].values
print(X[0:11,:])
y = df['HeartDiseaseorAttack'].values

print(y[0:10])
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier

rf=RandomForestClassifier()
rf.fit(X_train,y_train)

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

from sklearn import tree
from sklearn.tree import plot_tree
# Print the number of trees in the RF model
print("Number of trees in the RF model: ",len(classifier.estimators_))

# Plot the first 5 Trees in the FR model
for i in range(min(len(classifier.estimators_),5)):
  # Extract each individual decision tree from the Random Forest
  individual_tree = classifier.estimators_[i]
  # Visualize each decision tree
  plt.figure(figsize=(10, 8))
  plot_tree(individual_tree, filled=True)

plt.show()
#dont understand this

from sklearn.metrics import accuracy_score
y_pred=rf.predict(X_test)
accuracy_score(y_test,y_pred)

classifier.predict(X_test)

np.array(y_test)

from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
print(cm)
print(cr)